task 4
ozonmp/rcn-production-api pull request #3
Opened 2021-11-10 20:41 UTC by nikitacrit

2021-11-12 17:55 UTC, LiFeAiR requested changes

2021-11-12 17:55 UTC, LiFeAiR commented on internal/app/repo/event.go
> +	query := `
а что если использовать какой то пакет для генерации sql запросов?

2021-11-12 17:55 UTC, LiFeAiR commented on internal/repo/repo.go
> +	defer rollback(tx)
странно делать ролике транзакции на defer, а что будет при hapypath?

2021-11-12 17:55 UTC, LiFeAiR commented on internal/repo/repo.go
> +	if err = tx.Commit(); err != nil {
hapypath тут

2021-11-12 17:55 UTC, LiFeAiR commented on migrations/1_init.sql
> +    id            BIGSERIAL,
тут тоже `CONSTRAINT production_event_pk PRIMARY KEY`?

2021-11-12 20:07 UTC, nikitacrit commented on internal/repo/repo.go
> +	defer rollback(tx)
https://golang.org/doc/database/execute-transactions
![image](https://user-images.githubusercontent.com/74061731/141528237-b30923a3-ee28-4721-bce5-bb03b7250c9e.png)

2021-11-12 20:08 UTC, nikitacrit commented on internal/repo/repo.go
> +	if err = tx.Commit(); err != nil {
ответ выше

2021-11-12 20:16 UTC, nikitacrit commented on migrations/1_init.sql
> +    id            BIGSERIAL,
В первом коммите по дз (основная часть) у меня pk это только id + индекс по status. В следующем коммите там уже CONSTRAINT production_event_pk PRIMARY KEY (id, status) для партиции по status. Или ты намекаешь на пару id + production_id? У меня в приложении нет запросов с джоинами ивентов к продукту, а так же нету запросов которые выбирают ивенты по продукту. Т.е. он пока не требуется, а создавать лишний индекс в таблицу ивентов где мне нужен максимально быстрый инсерт просто так я не захотел. Если будут нужны вышеперечисленные запросы - будет создан такой pk.

2021-11-12 20:19 UTC, nikitacrit commented on internal/app/repo/event.go
> +	query := `
Спрашивал по этому вопросу у тебя в slack. Удобно ли читать многоэтажные запросы построенные на squirrel? Лично мне нет. + Я не нашел поддержки CTE в squirrel. Плохо искал? Могу переписать нет проблем.

2021-11-13 00:41 UTC, nikitacrit commented on internal/app/repo/event.go
> +	query := `
Исправил, но лично мое мнение:

2021-11-13 00:41 UTC, nikitacrit commented on internal/app/repo/event.go
> +	query := `
Исправил, но мое мнение.

2021-11-13 00:52 UTC, nikitacrit commented on internal/app/repo/event.go
> +	query := `
Исправил но мое мнение:
1. Читается очень плохо
2. Ограничения библиотеки особенно себя показывают на больших запросах.
3. WHERE field IN (subquery) через Prefix("field IN (").Suffix(")") не радует.
4. Если объектом передаваемым в Where() является не "SelectBuilder", а как у меня в запросе "And" (для условия where field1 in (select field from ...) and field2 > 0) то библиотека перестает выстраивать аргументы в нужном порядке. В моем случае пока все обошлось так как я могу использовать литералы но все шатко. Что можно сделать? Переписать на join может поможет. Обернуть в еще один подзапрос в надежде что план не развалится? А если у меня будет не AND а OR такой трюк уже не прокатит. В любом случае мы подстраиваемся под ограничения библиотеки. 
![image](https://user-images.githubusercontent.com/74061731/141599117-1fc53e6b-7436-462b-a9ff-90c2059385a3.png)

2021-11-13 02:19 UTC, nikitacrit commented on internal/app/repo/event.go
> +	query := `
Исправил но мое мнение:
Читается не приятно. Ограничения библиотеки особенно себя показывают на больших запросах. WHERE field IN (subquery) через Prefix("field IN (").Suffix(")") не радует. Если объектом передаваемым в Where() является не "SelectBuilder", а как у меня в запросе "And" (к примеру для условия where field1 in (select field from ...) and field2 > 0) то библиотека перестает выстраивать аргументы в нужном порядке. В моем случае пока все обошлось так как я могу использовать литералы но как-то шатко. Кстати в репе библиотеки много ишью на эту тему и очень даже старых. Что можно сделать? Переписать на join может поможет. Обернуть в еще один подзапрос в надежде что план не развалится? А если у меня будет не AND а OR такой трюк уже не прокатит. В любом случае мы подстраиваемся под ограничения библиотеки. В следующем доп задании использую CTE которые нативно тоже не поддерживаются. В общем пока не уверен в использовании сквирела на больших сложных запросах.

2021-11-13 02:19 UTC, nikitacrit commented on internal/app/repo/event.go
> +	query := `
Исправил но мое мнение:
Читается не приятно. Ограничения библиотеки особенно себя показывают на сложных запросах. WHERE field IN (subquery) через Prefix("field IN (").Suffix(")") не радует. Если объектом передаваемым в Where() является не "SelectBuilder", а как у меня в запросе "And" (к примеру для условия where field1 in (select field from ...) and field2 > 0) то библиотека перестает выстраивать аргументы в нужном порядке. В моем случае пока все обошлось так как я могу использовать литералы но как-то шатко. Кстати в репе библиотеки много ишью на эту тему и очень даже старых. Что можно сделать? Переписать на join может поможет. Обернуть в еще один подзапрос в надежде что план не развалится? А если у меня будет не AND а OR такой трюк уже не прокатит. В любом случае мы подстраиваемся под ограничения библиотеки. В следующем доп задании использую CTE которые нативно тоже не поддерживаются. В общем пока не уверен в использовании сквирела на больших сложных запросах.

2021-11-13 02:44 UTC, nikitacrit commented on internal/app/repo/event.go
> +	query := `
![image](https://user-images.githubusercontent.com/74061731/141602923-7845f234-09c0-43f5-9800-1da04396a580.png)

2021-11-13 22:15 UTC, nikitacrit commented on internal/app/repo/event.go
> +	query := `
Потестировал запрос - оказался не самым оптимальным, план плохой (оптимизатор не справился с IN (...)). В процессе исправления заодно перепишу на сквирел.

2021-11-14 22:13 UTC, nikitacrit commented on internal/app/repo/event.go
> +	query := `
Исправил

2021-11-15 20:32 UTC, LiFeAiR approved these changes

2021-11-16 16:46 UTC, merged