task 5
ozonmp/rcn-production-api pull request #4
Opened 2021-11-17 07:19 UTC by nikitacrit

2021-11-21 19:48 UTC, LiFeAiR requested changes

2021-11-21 19:48 UTC, LiFeAiR commented on cmd/rcn-production-api/main.go
> +		metricsServer := metrics.NewMetricsServer(&cfg)
если запускаешь что то в горутине, надо оставлять контекст или канцелл для отмены
а то будет утечка горутин и/или некорректное завершение приложения

2021-11-21 19:48 UTC, LiFeAiR commented on internal/app/producer/kafka.go
> +					metrics.TotalProductionEventProcessed.Inc()
а тут точно прибавляется только единичка, а не `n`?

2021-11-21 19:48 UTC, LiFeAiR commented on internal/repo/repo.go
> +func logMsg(ctx context.Context, method, msg, payload string) {
может эти функции сделать частью `repo`?

2021-11-21 19:48 UTC, LiFeAiR commented on internal/api/api.go
> +func logCtx(ctx context.Context) (context.Context, error) {
может эти функции сделать частью `productionAPI`?

2021-11-21 21:46 UTC, nikitacrit commented on cmd/rcn-production-api/main.go
> +		metricsServer := metrics.NewMetricsServer(&cfg)
Исправил через defer shutdown. это было плохо.

2021-11-21 21:46 UTC, nikitacrit commented on internal/app/producer/kafka.go
> +					metrics.TotalProductionEventProcessed.Inc()
Исправил это ошибка :(

2021-11-21 21:48 UTC, nikitacrit commented on internal/repo/repo.go
> +func logMsg(ctx context.Context, method, msg, payload string) {
думал об этом, но засомневался так как там не требовался ресивер хотя архитектурно конечно напрашивалось. исправил

2021-11-21 21:48 UTC, nikitacrit commented on internal/api/api.go
> +func logCtx(ctx context.Context) (context.Context, error) {
исправил

2021-11-27 01:07 UTC, LiFeAiR approved these changes

2021-11-27 20:19 UTC, merged